### PR TITLE
Implements search by case id

### PR DESCRIPTION
**Pull request by dc2007git**
### Overview

Allows a logged in user to search for a specific case by that case's unique id

### Code changes

Adds extra filter queries in case_views.py

### Related Issues

Closes issue #799

### CODE REVIEW

**Review by eatyourpeas — COMMENTED** [review]
This all looks good to me thank you Danny. 
Could you add an update to the tool tip in the input box to say that filtering is by name, nhs number and epilepsy 12 id?

**Comment by mbarton** [comment]
@dc2007git I'll have a look at your failing test - it looks related to the api server downtime and not your changes

**Comment by dc2007git** [comment]
> This all looks good to me thank you Danny. Could you add an update to the tool tip in the input box to say that filtering is by name, nhs number and epilepsy 12 id?

Yes I will do, cheers Simon

**Comment by dc2007git** [comment]
> @dc2007git I'll have a look at your failing test - it looks related to the api server downtime and not your changes

Thanks for this Michael. Let me know what you manage to find out!

**Comment by mbarton** [comment]
The tests are passing now - I had misconfigured the API server to use the Growth Charts Open API spec for the deprivation API

**Comment by eatyourpeas** [comment]
nice job @mbarton 
The census platform is quite lightweight now: [Pull request here](https://github.com/rcpch/rcpch-census-platform/pull/22)
It is dockerized, has 3 containers - one for caddy, one of docs, one for sqlite3 and django. It now also has some tests. Might be nice to use this or a form of it rather than what is there now.

Any way, I will merge this if you give your blessing @mbarton

**Pull request merged**
