### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by pacharanero**
adds email field to model to enable this to be shown in the UI

### CODE REVIEW

**Comment by pacharanero** [comment]
OK so @dc2007git it looks to me like this PR breaks some tests (tests fail locally on `ui-improvements` but pass locally on `development`)
Tests also failing in GH runner.

```
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.ORGANISATION-abstraction_codes0-ods_codes0] - epilepsy12.models_folder.kpi_aggregation.OrganisationKPIAggregation.MultipleObjectsReturned: get() retur...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.TRUST-abstraction_codes1-ods_codes1] - epilepsy12.models_folder.kpi_aggregation.TrustKPIAggregation.MultipleObjectsReturned: get() returned mor...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.LOCAL_HEALTH_BOARD-abstraction_codes2-ods_codes2] - epilepsy12.models_folder.kpi_aggregation.LocalHealthBoardKPIAggregation.MultipleObjectsReturned: get() r...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.ICB-abstraction_codes3-ods_codes3] - epilepsy12.models_folder.kpi_aggregation.ICBKPIAggregation.MultipleObjectsReturned: get() returned more ...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.NHS_ENGLAND_REGION-abstraction_codes4-ods_codes4] - epilepsy12.models_folder.kpi_aggregation.NHSEnglandRegionKPIAggregation.MultipleObjectsReturned: get() r...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.OPEN_UK-abstraction_codes5-ods_codes5] - epilepsy12.models_folder.kpi_aggregation.OpenUKKPIAggregation.MultipleObjectsReturned: get() returned mo...
FAILED epilepsy12/tests/common_view_functions_tests/aggregate_by_tests/test_update_kpiaggregation_model.py::test_update_kpi_aggregation_model_all_levels[EnumAbstractionLevel.COUNTRY-abstraction_codes6-ods_codes6] - epilepsy12.models_folder.kpi_aggregation.CountryKPIAggregation.MultipleObjectsReturned: get() returned m...
```

Might need to look through these in a bit more detail when we have time @anchit-chandran.

I suspect it is likely to be related to the addition of `email` fields in the Organisation model

**Comment by dc2007git** [comment]
Commit 54f0773 closes #696

**Comment by anchit-chandran** [comment]
@dc2007git is this definitely based on the most recent live? i fixed this test issue in a PR last week

**Comment by pacharanero** [comment]
@anchit-chandran - Danny merged development into this branch yesterday in order to update it, but possibly because this was a merge and not a rebase it's possible some of the updates didn't make it into the updated version of his branch?

Which part of the codebase caused this error? (ie where would we look to see if he has your fix in there?)
I can take a look with Danny next week and maybe find which commits are causing the issue.

**Pull request closed without merging**
