### PR TITLE
Implements 2fa

### PR DESCRIPTION
**Pull request by anchit-chandran**
Implements 2factorauth, with options for email or authenticator app (specified as Microsoft Authenticator).

Also hooks into @login_required decorator to first apply login check, and then 2fa check - updated for all relevant views.

Pls before approval, test the workflow yourselves - does it make intuitive sense / is the wording all fine?

**NOTE: this requires rebuilding the docker container**

## Workflow

Now, wherever login required, there is an extra 2fa step. If 2fa is not enabled yet, after login you are taken to the new Account page, informed to enable 2fa:

image

You're taken through a 'wizard' section , enabling either via email or authenticator app:

image

image

Then, the next time you log in, you will be asked for token.

### CODE REVIEW

**Review by eatyourpeas — CHANGES_REQUESTED** [review]
This is great thank you Anchit for implementing. I have got it working and followed the work flow using the microsoft authenticator works nicely. Having set the method of authentication to MS Authenticator and then changed it subsequently to email, it seems not possible to change it back, and the UI could maybe be clearer that the admin link in the navbar is where this is set. 
Could we perhaps run through this together tomorrow, make any small changes as necessary and then close?

**Comment by anchit-chandran** [comment]
> This is great thank you Anchit for implementing. I have got it working and followed the work flow using the microsoft authenticator works nicely. Having set the method of authentication to MS Authenticator and then changed it subsequently to email, it seems not possible to change it back, and the UI could maybe be clearer that the admin link in the navbar is where this is set. Could we perhaps run through this together tomorrow, make any small changes as necessary and then close?

Pair programmed today and worked through workflow + fixed other misc issues

Will still require some user testing @AmaniKrayemRCPCH to ensure it makes sense to fresh eyes.

**Comment by AmaniKrayemRCPCH** [comment]
Amazing! 

We can show to the audit team at RCPCH to get some fresh eyes. Let me know when that's possible.

**Review by eatyourpeas — APPROVED** [review]
Looking good now Anchit thank you

**Pull request merged**
