### PR TITLE
Multiple UI issues addressed

### LINKED ISSUE #679: Cohort view frame should be purple
image

The frame for the cohort view should match the segment header and footer

### LINKED ISSUE #697: Repeated heading text in DESSCRIBE - refactor the source of the text
As an example this is one heading, but many of the headings have some repetition or slightly confusing wording

image

### LINKED ISSUE #699: Consider emboldening this text in all main questions?
Just to make the main questions stand out a little more, I wonder if emboldening the text of (in this example) "Consultant paediatrician with expertise in epilepsies" would be nice?

image

### LINKED ISSUE #701: Consent and Performance Summary - positioning of Patient Name
Should be a simple fix but in the questions 8 and 9 of the Audit, the patient's name is marged with the left side text, whereas in all previous screens it is pulled right and separate, and includes the NHS number

### Example

7. Treatment and Care Planning
image

8. Consent (we need to change the heading "consent" probably anyway, see #700)
image

9. Performance Summary
image

### LINKED ISSUE #720: Create user form errors showing raw errors
On the live site, creating a new user form with errors shows errors raw for the `__all__` field key (email must be unique).

Instead, change to nicer wording, don't display '__all__' like that

Image

### LINKED ISSUE #721: Placeholder form values in register child for audit could be nicer
Before date of first paediatric assessment date is set, these placeholders will be None. Could be improved to something more readable, even just `"-"`

Image

### LINKED ISSUE #729: Updates to organisations - Add 2, remove 1
These are updates to the organisations under Sherwood Forest Hospitals NHS Foundation Trust, as requested by @coldunk 

Add the following:
```
    {
        "OrganisationID": "",
        "OrganisationCode": "RK5HP",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "NEWARK HOSPITAL",
        "Address1": "BOUNDARY ROAD",
        "Address2": "",
        "Address3": "",
        "City": "NEWARK",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG24 4DE",
        "Latitude": "53.06751",
        "Longitude": "-0.80616",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E10000024",
    },
    {
        "OrganisationID": "",
        "OrganisationCode": "RK5CP",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "KMH COMMUNITY PAEDIATRICIANS",
        "Address1": "KINGS MILL HOSPITAL",
        "Address2": "MANSFIELD ROAD",
        "Address3": "",
        "City": "SUTTON-IN-ASHFIELD",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG17 4JL",
        "Latitude": "53.13455582",
        "Longitude": "-1.233566165",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "sfh-tr.pet@nhs.net",
        "Website": "http://www.sfh-tr.nhs.uk",
        "Fax": "01623 621770",
        "LocalAuthority": "E07000170",
    },
```

Remove the following:
```
    {
        "OrganisationID": "",
        "OrganisationCode": "RK540",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "SHERWOOD COMMUNITY HEALTH CENTRE",
        "Address1": "ELMSWOOD GARDENS",
        "Address2": "",
        "Address3": "",
        "City": "NOTTINGHAM",
        "County": "NOTTINGHAMSHIRE",
        "Postcode": "NG5 4AD",
        "Latitude": "52.98385661535865",
        "Longitude": "-1.1409483690398214",
        "ParentODSCode": "RK5",
        "ParentName": "SHERWOOD FOREST HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E06000018",
    },
```

### LINKED ISSUE #730: Fix ethnicity labelling
2 Tasks:

- [ ] When selecting ethnicity for a patient, the option from the NHS DMD for 'White British' actually shows up as 'Mixed British',  which is confusing. This corresponds to option A in the NHS DMD.
- [ ] The dropdown for ethnicities should ideally be in order, so 'White' categories are grouped together, 'Mixed' categories are grouped together

### LINKED ISSUE #736: Edit cause tooltip
Edit the tool tip on "What is the main identified cause of the epilepsy?" to say that, if the cause is not on the list, to contact E12 and we'll add it to the list. Something like: 
"Please select the main identified cause of the epilepsy. If the cause is not in this list, please email the Epilepsy12 team"

### PR DESCRIPTION
**Pull request by dc2007git**
Resolves #701 - On each audit question page, the patient name is kept to the far right of the screen
Resolves #736 - Edits tooltip to signpost E12 team upon a cause of epilepsy not being an option in a dropdown.
Resolves #720 - removes raw errors showing on user web page when an email or password error is thrown
Resolves #721 - fixes placeholder values in first paediatric assessment date
Resolves #699 - makes text bold for all main questions
Resolves #697 - removes repeated text in questions

Also conditionally renders email field (this time it works, no problems with migrations), resolves issue #669 

Adds an email field to the YSBYTY YSTRAD FAWR object in rcpch_organisations.py which was previously missing.

Added in + slightly changed commits from @anchit-chandran in order to keep styling consistent between Organisation, User and Case dashboard as per #607 and #670 . Centers the titles of these pages and makes the width of the containers consistent as per figma.

Resolves #679 from Anchit's commit by making cohort view frame purple

Resolves #730 - updates ethnicity labels to new NHS DMD and reorders them in dropdown

Commit included for #684 - create a Cohort Card partial. Next step is to update the card itself to have both the active cohort and currently submitting cohort once the team agrees on a UI

### CODE REVIEW

**Comment by anchit-chandran** [comment]
Remaining issues which can be added into this PR:

- [x] #699 
- [x] #720 
- [x] #721

**Comment by dc2007git** [comment]
> Remaining issues which can be added into this PR:
> 
> * [x]  [Consider emboldening this text in all main questions? #699](https://github.com/rcpch/rcpch-audit-engine/issues/699)
> * [x]  [Create user form errors showing raw errors #720](https://github.com/rcpch/rcpch-audit-engine/issues/720)
> * [x]  [Placeholder form values in register child for audit could be nicer #721](https://github.com/rcpch/rcpch-audit-engine/issues/721)

These are already in the PR so will be merged tomorrow

**Comment by eatyourpeas** [comment]
These changes all look great. Nice work guys.

**Comment by pacharanero** [comment]
Extensive code review with @dc2007git @anchit-chandran @pacharanero
Rebuild and tests running locally and on Dev VPS
Some additional work pleasing the Linter
Fixed test which checked ethnicity data integrity, which was dependent on the old order of Ethnicities in the list.
Merging

**Pull request merged**
