### PR TITLE
Adds Country column to Country - Sheet 2

### LINKED ISSUE #924: Missing country column in KPI export

### PR DESCRIPTION
**Pull request by dc2007git**
### Overview

Adds the column 'Country' to sheet number 2 - 'Country'

### Code changes

Adds a line to the create_kpi_report_row function to render either 'England' or 'Wales' as the country and add it to the ret dictionary object

### Documentation changes (done or required as a result of this PR)

N/A

### Related Issues

Closes #924

### CODE REVIEW

**Comment by mbarton** [comment]
This works but I'd like to avoid putting sheet specific modifications low down in the call stack where we can. It makes it harder to understand what the low level function is doing without holding all the calling code in your head at the same time.

Could we add the extra column in `kpi.py` only for sheet 1? eg

[kpi.py:94](https://github.com/rcpch/rcpch-audit-engine/blob/c7bcb6956c523817c59f6e4ba3025e52789670ea/epilepsy12/kpi.py#L94)

```python
england_row = create_kpi_report_row(
    "england", measure_title, kpi, england_kpi_aggregation
)

england_row["Country"] = "England"

wales_row = create_kpi_report_row(
    "wales", measure_title, kpi, wales_kpi_aggregation
)

wales_row["Country"] = "Wales"
```

**Comment by dc2007git** [comment]
My mistake thanks for the suggestion @mbarton. Will push the changes to this PR

**Comment by mbarton** [comment]
Thanks @dc2007git! It's not a mistake on your part, just a suggestion on mine :)

**Comment by dc2007git** [comment]
@mbarton the most recent changes I've pushed to this PR can be discarded, as well as with this entire PR, because this is solved in a more holistic way in PR #926 , which means we can remove the unnecessary columns, reorganise the columns, and add the uk column all in one fell swoop!

**Pull request closed without merging**
