### PR TITLE
get-out-of-the-gulag

### PR DESCRIPTION
**Pull request by eatyourpeas**
### Overview

These changes that are a bit old but should have been in live some time back
They are fix to getting out of the gulag
There is also an older commit adding some epilepsy causes which are already live in the database but there for seeding purposes in the future

After this, the development branch can be deprecated

### CODE REVIEW

**Comment by mbarton** [comment]
Seen on [STAGING](https://e12-staging.rcpch.tech/) (merged by @eatyourpeas 12 minutes and 45 seconds ago) Please check your changes!

**Comment by mbarton** [comment]
Seen on [LIVE](https://e12.rcpch.ac.uk/) (merged by @eatyourpeas 12 minutes and 53 seconds ago) Please check your changes!

**Comment by mbarton** [comment]
@SAbdin93 and I have confirmed on a teams call this works - the user was able to register and set 2fa

**Comment by SAbdin93** [comment]
Thanks @mbarton @eatyourpeas

**Pull request merged**
