### PR TITLE
optional-input-dates

### LINKED ISSUE #1095: Make 'date seen' field non-mandatory for paediatrician with expertise, neurologist & ESN
Please can the 'date seen' field for 1) paediatrician with expertise, 2) paediatric neurologist and 3) ESN (under Milestones section) be made non-mandatory? Example screenshot below:
Neurologist Q screenshot

There will be instances where CYP are referred to a paediatrician/neurologist/ESN but are not seen within the first year (or before the data submission deadline). Currently, we mandate a 'date seen' for each professional and the record cannot be completed unless a date is entered. 

This has somehow slipped through out testing and has strangely only just been raised by a user. We feel that this is very common in practice though, and it may be because the majority of data entry is occurring now before the deadline and the cohort are completing their year of care now that this problem is arising. 

I would be open to having a button that says 'not achieved yet' that overrides the 'date seen' field. However, we need this actioning asap so that users can complete records before the January 2025 deadline, so I feel making the field non-mandatory may be the quicker and best option for now?

### PR DESCRIPTION
**Pull request by eatyourpeas**
### Overview

This makes the input dates for paediatrician with expertise, neurologist and epilepsy specialist nurse all optional, and introduces input_achieved toggles that make them mandatory if selected.

The E12 team do not feel this has implications for the  KPI calculations

Generates 3 new fields in the Assessment model so will there is a new migration

closes #1095

### CODE REVIEW

**Comment by eatyourpeas** [comment]
just to add, it adds a final migration that retrospectively sets the `*_input_achieved` value to `True` for those existing records where `*_input_date` is not None. Screen shots of the changes are in the issue it closes.

**Comment by eatyourpeas** [comment]
@mbarton just because of the extra migration step at the end would be grateful if you could try out that bit and make sure it does what we expect - ie all existing records where `epilepsy_specialist_nurse_input_date`, `consultant_paediatrician_input_date` or `paediatric_neurologist_input_date` in the Assessment tab have existing dates, that they are visible in the ui and the `*_input_achieved` toggle is set to true

**Review by mbarton — APPROVED** [review]
Works as advertised for me - I tried each test case separately and all together as well as a patient who shouldn't have their field set by the migration at all

**Comment by mbarton** [comment]
Seen on [STAGING](https://e12-staging.rcpch.tech/) (merged by @eatyourpeas 28 minutes and 31 seconds ago) Please check your changes!

**Comment by mbarton** [comment]
Seen on [LIVE](https://e12.rcpch.ac.uk/) (merged by @eatyourpeas 28 minutes and 35 seconds ago) Please check your changes!

**Pull request merged**
