### PR TITLE
Remove delete site button

### LINKED ISSUE #772: Remove delete site button
The delete site function is causing confusion. It is therefore being removed.

### PR DESCRIPTION
**Pull request by eatyourpeas**
Fixes #772

### Overview

The red delete site button in the registration form is causing confusion and leading to users deleting the site, thinking they are deleting the child. By removing the button for all, this removes this vulnerability.

### Code changes

Remove the delete_site function from `registration_views`, from the urls and from the template.

### Documentation changes (done or required as a result of this PR)

Please describe any changes to documentation here.

### Related Issues

fixes #722

### CODE REVIEW

**Comment by dc2007git** [comment]
@eatyourpeas thanks for the review request - have had a look at your PR and happy with the functionality. Have also made a couple of commits myself:

- Removing comments referencing the can_delete_lead_site permission in testing files
- Removing references to the can_delete_lead_site permission

This means that all mentions of deleting lead site should now be gone. Just a thought - will this change the testing at all? I didn't see any changes to the test files in your PR.

**Comment by dc2007git** [comment]
It looks like the tests test_cases_aggregated_by_sex and test_cases_aggregated_by_ethnicity are failing, but only on GitHub - they pass as expected locally. The respective errors are as follows:

AssertionError: `cases_aggregated_by_sex` output does not match expected output for Male. Output 10 but expected 11.

and 

AssertionError: Expected aggregate count for cases_aggregated_by_ethnicity not matching output: aggregate={'ethnicity_display': 'White British', 'ethnicities': 10} should be expected_ethnicity_data={'ethnicity_display': 'White British', 'ethnicities': 11}

This error seems to also be affecting #775

**Comment by dc2007git** [comment]
This branch also has 34 tests which fail locally and raise ValueError: Missing staticfiles manifest entry for 'hyperscript_0.9.8/hyperscript.min.js'

Potential fix is mentioned in #775

**Review by dc2007git — COMMENTED** [review]
Happy that the functionality for removing the delete button works, however like Marcus has said there are commits that seem to be shared between these PRs as a result of my rebasing yesterday, so will need tidying up before we merge into develompent. Also, the hypersscript-related tests are still failing for me locally.

**Comment by pacharanero** [comment]
tested locally in UI and tests passing on GH actions

**Pull request merged**
